language: node_js
node_js: "12.19.0"
os: windows

before_install:
  - yarn

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Test
      script:
        - npm test
        - exit 0
    - stage: Deploy Windows
      script:
        - yarn make
        - exit 0
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "out\\make\\squirrel.windows\\x64\\*.exe"
  skip_cleanup: true
  draft: true
  